# frozen_string_literal: true

companies = [
  { name: 'Infosys', location: 'Hinjewadi Phase 1' },
  { name: 'Wipro', location: 'Hinjewadi Phase 2' },
  { name: 'Cognizant', location: 'Hinjewadi Phase 3' },
  { name: 'Tech Mahindra', location: 'Hinjewadi Phase 2' },
  { name: 'Tata Consultancy Services', location: 'Magarpatta City' },
  { name: 'Capgemini', location: 'Kalyani Nagar' },
  { name: 'Barclays', location: 'EON Free Zone, Kharadi' },
  { name: 'FIS', location: 'EON Free Zone, Kharadi' },
  { name: 'IBM India', location: 'Ozone IT Park, Hadapsar' },
  { name: 'Deloitte', location: 'ICC Tech Park, Shivajinagar' },
  { name: 'PTC', location: 'Weikfield IT Citi Info Park, Viman Nagar' },
  { name: 'Emcure Pharmaceuticals', location: 'Hinjewadi Phase 2' },
  { name: 'Accenture', location: 'Magarpatta City' },
  { name: 'Cybage Software', location: 'Kalyani Nagar' },
  { name: 'Persistent Systems', location: 'Baner' },
  { name: 'Zensar Technologies', location: 'Kharadi EON Park' },
  { name: 'Red Hat India', location: 'Magarpatta' },
  { name: 'DXC Technology', location: 'Hinjewadi' },
  { name: 'Rakuten India', location: 'Baner' },
  { name: 'BMC Software', location: 'Baner' },
  { name: 'Veritas Technologies', location: 'Baner' },
  { name: 'Nvidia', location: 'Yerwada' },
  { name: 'TransUnion', location: 'Kharadi' },
  { name: 'CrowdStrike', location: 'Kharadi' },
  { name: 'Deloitte', location: 'Viman Nagar' },
  { name: 'Mindtree', location: 'Magarpatta' },
  { name: 'WNS Global Services', location: 'Magarpatta' },
  { name: 'BytzSoft', location: 'Kharadi' },
  { name: 'Tietoevry', location: 'Hinjewadi' },
  { name: 'Deutsche Bank', location: 'Kharadi' },
  { name: 'Credit Suisse', location: 'Hinjewadi Phase 1' },
  { name: 'HSBC', location: 'Magarpatta City' },
  { name: 'BNY Mellon', location: 'Kharadi' },
  { name: 'Goldman Sachs', location: 'Baner' },
  { name: 'JPMorgan Chase', location: 'Hinjewadi Phase 2' },
  { name: 'Morgan Stanley', location: 'Viman Nagar' },
  { name: 'Amazon', location: 'Hinjewadi Phase 3' },
  { name: 'Google', location: 'Magarpatta City' },
  { name: 'Microsoft', location: 'Hinjewadi Phase 1' },
  { name: 'Oracle', location: 'Kharadi' },
  { name: 'SAP Labs', location: 'Hinjewadi Phase 2' },
  { name: 'Salesforce', location: 'Baner' },
  { name: 'Adobe', location: 'Magarpatta City' },
  { name: 'Intuit', location: 'Viman Nagar' },
  { name: 'Symantec', location: 'Hinjewadi Phase 3' },
  { name: 'Vmware', location: 'Kalyani Nagar' },
  { name: 'Cisco', location: 'Hinjewadi Phase 1' },
  { name: 'Juniper Networks', location: 'Kharadi' },
  { name: 'Qualcomm', location: 'Magarpatta City' },
  { name: 'UST Global', location: 'Kharadi' },
  { name: 'Cognizant Digital Works', location: 'Hinjewadi Phase 3' },
  { name: 'Publicis Sapient', location: 'Viman Nagar' },
  { name: 'Virtusa', location: 'Hinjewadi Phase 1' },
  { name: 'Sonata Software', location: 'Baner' },
  { name: 'ITC Infotech', location: 'Hinjewadi Phase 2' },
  { name: 'Mindtree', location: 'Kharadi' },
  { name: 'L&T Infotech', location: 'Magarpatta City' }

]

companies.each { |c| Company.find_or_create_by!(name: c[:name]) { |co| co.location = c[:location] } }
