Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "db/**/*.rb"

Metrics/AbcSize:
  Exclude:
    - "db/**/*.rb"
    -


Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false