services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:create db:migrate && bin/rails server -b '0.0.0.0'"
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgres://postgres:root@db/officebusbooking_development"
      REDIS_URL: "redis://redis:6380/1"
      OFFICEBUSBOOKING_DATABASE_PASSWORD: "root"
      RAILS_MASTER_KEY: "537ab01b5d5e52d70135400c5a63bdff"  # Add your master key here

  db:
    image: postgres:14
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: officebusbooking_development

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - "redis_data:/data"

volumes:
  postgres_data:
  redis_data:
